name: PipelineWorkflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Azure DevOps pipeline
        shell: bash
        env:
          AZURE_DEVOPS_TOKEN: ${{ secrets.AZURE_DEVOPS_TOKEN }}
        run: |
          curl --fail-with-body \
            --user ":${AZURE_DEVOPS_TOKEN}" \
            --header "Content-Type: application/json" \
            --request POST \
            --data '{
              "resources": {
                "repositories": {
                  "self": {
                    "refName": "refs/heads/master"
                  }
                }
              }
            }' \
            "https://dev.azure.com/ddjenkins050284/JobInterview/_apis/pipelines/4/runs?api-version=7.1"
`
